export const Teams = {
    "ARI": {"city":"Arizona", "mascot":"Cardinals"},
    "ATL": {"city":"Atlanta", "mascot":"Falcons"},
    "BAL": {"city":"Baltimore", "mascot":"Ravens"},
    "BUF": {"city":"Buffalo", "mascot":"Bills"},
    "CAR": {"city":"Carolina", "mascot":"Panthers"},
    "CHI": {"city":"Chicago", "mascot":"Bears"},
    "CIN": {"city":"Cincinnati", "mascot":"Bengals"},
    "CLE": {"city":"Cleveland", "mascot":"Browns"},
    "DAL": {"city":"Dallas", "mascot":"Cowboys"},
    "DEN": {"city":"Denver", "mascot":"Broncos"},
    "DET": {"city":"Detroit", "mascot":"Lions"},
    "GB": {"city":"Green Bay", "mascot":"Packers"},
    "HOU": {"city":"Houston", "mascot":"Texans"},
    "IND": {"city":"Indianapolis", "mascot":"Colts"},
    "JAC": {"city":"Jacksonville", "mascot":"Jaguars"},
    "KC": {"city":"Kansas City", "mascot":"Chiefs"},
    "MIA": {"city":"Miami", "mascot":"Dolphins"},
    "MIN": {"city":"Minnesota", "mascot":"Vikings"},
    "NYG": {"city":"New York", "mascot":"Giants"},
    "NYJ": {"city":"New York", "mascot":"Jets"},
    "NE": {"city":"New England", "mascot":"Patriots"},
    "NO": {"city":"New Orleans", "mascot":"Saints"},
    "OAK": {"city":"Oakland", "mascot":"Raiders"},
    "PHI": {"city":"Philadelphia", "mascot":"Eagles"},
    "PIT": {"city":"Pittsburgh", "mascot":"Steelers"},
    "LAC": {"city":"Los Angeles", "mascot":"Chargers"},
    "SF": {"city":"San Francisco", "mascot":"49ers"},
    "SEA": {"city":"Seattle", "mascot":"Seahawks"},
    "LAR": {"city":"Los Angeles", "mascot":"Rams"},
    "TB": {"city":"Tampa Bay", "mascot":"Buccaneers"},
    "TEN": {"city":"Tennessee", "mascot":"Titans"},
    "WAS": {"city":"Washington", "mascot":"Redskins"},
}